CREATE TABLE "ACCOUNT_MAP" 
(	
	"PARENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CHILD_ID" NUMBER(38,0) NOT NULL ENABLE,  
  CONSTRAINT "ACCOUNT_MAP_UK1" UNIQUE ("CHILD_ID", "PARENT_ID") USING INDEX (CREATE INDEX "ACCOUNT_MAP_INDEX2" ON "ACCOUNT_MAP" ("CHILD_ID","PARENT_ID")),
  CONSTRAINT "ACCOUNT_MAP_UK2" UNIQUE ("CHILD_ID") USING INDEX (CREATE INDEX "ACCOUNT_MAP_INDEX1" ON "ACCOUNT_MAP" ("CHILD_ID")),
  CONSTRAINT "ACCOUNT_MAP_FK1" FOREIGN KEY ("PARENT_ID") REFERENCES "ACCOUNTS" ("STATION_ID"),
  CONSTRAINT "ACCOUNT_MAP_FK2" FOREIGN KEY ("CHILD_ID") REFERENCES  "ACCOUNTS" ("STATION_ID")
);

update version_number set version_number=270, min_version_number=270;
